name = "test-om-api"
compatibility_date = "2026-05-21"

# This allows `npx wrangler deploy` to deploy the static HTML as a Worker with assets.
# If you are using Cloudflare Pages Git integration instead, you usually do not need this file.
assets = { directory = "./public" }
